### ISSUE TITLE
refactoring motivation

### ISSUE THREAD

**Issue by andrey-lazarev** [andrey-lazarev/pizza-delivery-task-react-redux-ts#32]
Today the repository has been thoroughly reviewed by one of my potential employers and the next critical design flaws were brought to my attention, which I knew about but conscientiously ignored: 

> 1. action-функции раскиданы по проекту - лежат, как в подкаталоге store, так и в каталогах компонентов;

> 2. запутанная логика (а скорее всего велосипед), связанный с работой с формами: action-функции getFormInput, onInputBlur, setFormInputValue, setFormInputIsValid. Лучше использовать проверенные годами решения типа formik, react-final-form, redux-form и т.п.;

> 3. FormComponent используется только внутри FormHOC и скорее всего никогда без него использоваться не будет, поэтому логичнее было бы их расположить не на одном уровне, а вложить FormComponent в каталог FormHOC;

> 4. вообще идея разделения на умные (FormHOC) и глупые (FormComponent) компоненты здравая, но для этого выбрана не лучшая структура проекта;

> 5. не увидел возможности для расширения приложения - когда возможен вариант открытия одного модального окна из другого или вместо другого, когда есть несколько форм;

> 6. работа с роутингом на достаточно примитивном уровне;

> 7. архитектурный аспект: компоненты Modal и Form, которые по своей сути не должны были быть связаны между собой оказались абсолюно взаимосвязаны;

In the refactoring branch, I'll take a chance to address these issues.

**TODO:**
- [x] bring actions in order -- ALL actions are in place, the reviewer took actionCreator events for simple actions.;
- [ ] remove obscure complexity from Form logic, but I prefer not to use ready-made solutions, rather look upon the best practices;
- [ ] refactor FormComponent, FormHOC to mitigate points 3 and 4;
- [ ] review and refactor Modal and Form components, to foresee and prevent the extendability issues;
- [ ] I disagree with point 6 as a flaw, as I see no need to make routing any more advanced, however, I'll let that idea sink into my mind and create at least the 404 page, or consider some auto-redirects;
- [ ] separate Modal logic from Form logic.
